name: Testing
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Mostrar árvore de arquivos
      run: ls -R

    - name: Versão do Python
      run: python3 --version

    - name: Instalar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Mostrar pacotes instalados
      run: pip list

    - name: Rodar testes
      run: python manage.py test --verbosity 2